version: '2'

services:
  csswrapper:
    image: bde2020/nginx-proxy-with-css:latest
    ports:
      - "80:80"
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro

  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    links:
      - csswrapper
    environment:
      CLUSTER_NAME: "test"
      VIRTUAL_HOST: "namenode.big-data-europe.local"
      VIRTUAL_PORT: "50070"
      CSS_SOURCE: "hadoop"
    env_file:
      - ./hadoop.env
