version: '2'

services:
  nginx:
    build: ./frontend
    ports:
      - "80:80"

  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    links:
      - nginx
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.0.0
    links:
      - nginx
      - namenode
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:1.0.0
    links:
      - nginx
      - namenode
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:1.0.0
    links:
      - nginx
      - namenode
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    links:
      - nginx
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  #
  # FileBrowser block
  #

  hdfsfb:
    image: bde2020/hdfs-filebrowser:3.9
    links:
      - nginx
      - namenode
    environment:
      - NAMENODE_HOST=namenode

  #
  # Spark configuration block
  #

  spark-master:
    image: bde2020/spark-master:1.5.1-hadoop2.6
    links:
      - nginx
    environment:
      INIT_DAEMON_STEP: setup_spark

  spark-worker:
    image: bde2020/spark-worker:1.5.1-hadoop2.6
    links:
      - nginx
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  flink-master:
    image: bde2020/flink-master:0.10.1-hadoop2.7
    links:
      - nginx
    environment:
      - INIT_DAEMON_STEP=setup_flink

  flink-worker:
    image: bde2020/flink-worker:0.10.1-hadoop2.7
    links:
      - nginx
      - flink-master

  solr:
    image: earthquakesan/solr:1.0.0-solr6.0.1
    links:
      - nginx
      - zookeeper
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181

  zookeeper:
    image: mesoscloud/zookeeper:3.4.8-centos-7
    links:
      - nginx
    environment:
      - MYID=1

  strabon:
    image: bde2020/strabon
    links:
      - nginx

  sextant:
    image: bde2020/sextant
    links:
      - nginx

  integrator-ui:
    build: ./integrator-ui
    links:
      - nginx
