nginx:
  build: ./frontend
  hostname: nginx
  net: hadoop
  container_name: nginx
  environment:
    - VIRTUAL_HOST=hadoop.vhost.tld
    - VIRTUAL_HOST=hdfsfb.vhost.tld
    - VIRTUAL_HOST=spark.vhost.tld
    - VIRTUAL_HOST=solr.vhost.tld
    - VIRTUAL_HOST=flink.vhost.tld
  ports:
    - "80:80"

#
# Hadoop block
#

namenode:
  image: bde2020/hadoop-namenode:1.0.0
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/namenode:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=test
  env_file:
    - ./hadoop.env

resourcemanager:
  image: bde2020/hadoop-resourcemanager:1.0.0
  hostname: resourcemanager
  container_name: resourcemanager
  domainname: hadoop
  net: hadoop
  env_file:
    - ./hadoop.env

historyserver:
  image: bde2020/hadoop-historyserver:1.0.0
  hostname: historyserver
  container_name: historyserver
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/historyserver:/hadoop/yarn/timeline
  env_file:
    - ./hadoop.env

nodemanager1:
  image: bde2020/hadoop-nodemanager:1.0.0
  hostname: nodemanager1
  container_name: nodemanager1
  domainname: hadoop
  net: hadoop
  env_file:
    - ./hadoop.env

datanode1:
  image: bde2020/hadoop-datanode:1.0.0
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode1:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

#
# FileBrowser block
#

hdfsfb:
  image: bde2020/hdfs-filebrowser:3.9
  hostname: hdfsfb
  container_name: hdfsfb
  domainname: hadoop
  net: hadoop
  environment:
    - NAMENODE_HOST=namenode

#
# Spark configuration block
#

spark-master:
  image: bde2020/spark-master:1.5.1-hadoop2.6
  hostname: spark-master
  container_name: spark-master
  net: hadoop
  environment:
    INIT_DAEMON_STEP: setup_spark

spark-worker:
  image: bde2020/spark-worker:1.5.1-hadoop2.6
  net: hadoop
  environment:
    - SPARK_MASTER=spark://spark-master:7077

#
# Flink configuration block
#

flink-master:
  image: bde2020/flink-master:0.10.1-hadoop2.7
  hostname: flink-master
  container_name: flink-master
  environment:
    - INIT_DAEMON_STEP=setup_flink
  net: hadoop
flink-worker:
  image: bde2020/flink-worker:0.10.1-hadoop2.7
  hostname: flink-worker
  container_name: flink-worker
  net: hadoop

#
# Solr configuration block
#

solr:
  image: earthquakesan/solr:1.0.0-solr6.0.1
  hostname: solr
  container_name: solr
  environment:
    - ZOOKEEPER_HOST=zookeeper:2181
  net: hadoop
zookeeper:
  image: mesoscloud/zookeeper:3.4.8-centos-7
  hostname: zookeeper
  container_name: zookeeper
  net: hadoop
  environment:
    - MYID=1
