version: '2'

services:
  csswrapper:
    image: bde2020/nginx-proxy-with-css:latest
    ports:
      - "80:80"
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro

  semagrow:
    image: semagrow/semagrow
    links:
      - csswrapper
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: "semagrow.big-data-europe.aksw.org"
      VIRTUAL_PORT: "8080"
      CSS_SOURCE: "semagrow"

  integrator-ui:
    build: ./integrator-ui-semagrow
    links:
      - csswrapper
    environment:
      VIRTUAL_HOST: "integrator-ui.big-data-europe.aksw.org"
